# Generated by Django 4.0.3 on 2022-07-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0003_remove_employervacancyregistration_user_and_more'),
        ('applicants', '0005_remove_applicantprofile_video_applicantvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantVacancyPostulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postulated_time', models.DateTimeField(auto_now_add=True)),
                ('link_video', models.URLField(verbose_name='link_video')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulated_applicant', to='applicants.applicantprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulated_vacancy', to='employers.employervacancyregistration')),
            ],
            options={
                'verbose_name_plural': 'Postulations',
                'db_table': 'postulations',
            },
        ),
    ]
