# Generated by Django 4.0.3 on 2022-07-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_remove_applicantprofile_video_applicantvideo'),
        ('employers', '0004_employervacancyregistration_applicants'),
        ('postulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantvacancypostulation',
            unique_together={('applicant', 'vacancy')},
        ),
    ]
