# Generated by Django 4.0.3 on 2022-07-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arearol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Nombre de la empresa:')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción:')),
                ('logo', models.ImageField(upload_to='logo:')),
            ],
            options={
                'verbose_name': 'Empleador',
                'verbose_name_plural': 'Empleadores',
                'db_table': 'employer',
                'ordering': ['company_name', 'description', 'logo'],
            },
        ),
        migrations.CreateModel(
            name='EmployerVacancyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo')], default='', max_length=100, verbose_name='Tipo de trabajo:')),
                ('modality', models.CharField(choices=[('Presencial', 'Presencial'), ('Home office', 'Home office'), ('Híbrido', 'Híbrido')], default='', max_length=50, verbose_name='Modalidad:')),
                ('job_description', models.CharField(max_length=500, verbose_name='Descripción del puesto:')),
                ('requierements', models.CharField(max_length=500, verbose_name='Requisitos:')),
                ('video_explanation', models.URLField(verbose_name='Video explicativo:')),
                ('salary', models.CharField(max_length=50, verbose_name='Sueldo:')),
                ('question_1', models.CharField(max_length=500, verbose_name='Pregunta 1:')),
                ('question_2', models.CharField(max_length=500, verbose_name='Pregunta 2:')),
                ('question_3', models.CharField(max_length=500, verbose_name='Pregunta 3:')),
                ('state', models.CharField(choices=[('AGS', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHI', 'Chihuahua'), ('CMX', 'Ciudad de México'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DUR', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], default='', max_length=30, verbose_name='Estado:')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipio:')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arearol.area', verbose_name='Área:')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arearol.rol', verbose_name='Rol:')),
            ],
            options={
                'db_table': 'employer_vacancy_registration',
            },
        ),
    ]
