# Generated by Django 4.0.3 on 2022-07-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employervacancyregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='employervacancyregistration',
            name='employer_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='register_vacancy', to='employers.employerprofile'),
            preserve_default=False,
        ),
    ]
