# Generated by Django 4.0.3 on 2022-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_remove_applicantprofile_video_applicantvideo'),
        ('employers', '0003_remove_employervacancyregistration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employervacancyregistration',
            name='applicants',
            field=models.ManyToManyField(through='postulations.ApplicantVacancyPostulation', to='applicants.applicantprofile'),
        ),
    ]
