# Generated by Django 4.0.3 on 2023-04-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employervacancyregistration_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employervacancyregistration',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='employervacancyregistration',
            name='area',
        ),
        migrations.RemoveField(
            model_name='employervacancyregistration',
            name='employer_profile',
        ),
        migrations.RemoveField(
            model_name='employervacancyregistration',
            name='rol',
        ),
    ]
