databases:
  - name: ch264h5269v61fbviui0
    databaseName: get_talent
    user: get_talent_user

 services:
 - type: pserv
   name: pgbouncer
   env: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: postgres://get_talent_user:u4jHMl5UNA7CafgybFqh6tmPnaIEuonQ@dpg-ch264h5269v61fbviui0-a/get_talent
     fromDatabase:
       name: ch264h5269v61fbviui0
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50