# Generated by Django 4.0.3 on 2022-07-20 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0001_initial'),
        ('arearol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantvideo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantjobinterest',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arearol.area', verbose_name='Area:'),
        ),
        migrations.AddField(
            model_name='applicantjobinterest',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arearol.rol', verbose_name='Rol:'),
        ),
        migrations.AddField(
            model_name='applicantjobinterest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_interest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to=settings.AUTH_USER_MODEL),
        ),
    ]
