# Generated by Django 4.0.3 on 2022-07-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='video',
            field=models.URLField(default='', verbose_name='video'),
        ),
    ]
